Weapons now selectable in shop
Nolle10/InVasion pull request #63
Opened 2023-05-12 17:50 UTC by Crazi12345

Hope you enjoy

2023-05-12 18:33 UTC, Crazi12345 commented
I have also made a second weapon module

2023-05-13 07:55 UTC, KatBirk requested changes
Make checks in shopstate when using values from weapon lists so game doesn't crash if lists have nothing in them

2023-05-13 10:49 UTC, CamillaFrank commented on GameEngine/src/main/java/dk/sdu/se/f23/InVasion/gamestates/ShopState.java
>          gsm.getGameData().addProcessor(stage);
Ryk  gsm.getGameData().addProcessor(stage)  ned i slutningen af metoden, så det først gøres når alle actors er tilføjet til stage. Det kan skabe problemer med input ellers :)

2023-05-13 10:50 UTC, CamillaFrank commented on GameEngine/src/main/java/dk/sdu/se/f23/InVasion/gamestates/ShopState.java
> +                        System.out.println("CLICKED");
Fjern test prints

2023-05-14 14:46 UTC, Crazi12345 commented on GameEngine/src/main/java/dk/sdu/se/f23/InVasion/gamestates/ShopState.java
>          gsm.getGameData().addProcessor(stage);
done, dog er der måske et problem med at jeg dynamisk adder og remove items fra stage, dog har de ikke en click handler? @CamillaFrank

2023-05-14 15:00 UTC, Darchie4 approved these changes
LGTM

2023-05-14 15:51 UTC, KatBirk approved these changes

2023-05-14 15:51 UTC, merged

2023-05-14 18:35 UTC, CamillaFrank commented on GameEngine/src/main/java/dk/sdu/se/f23/InVasion/gamestates/ShopState.java
>          gsm.getGameData().addProcessor(stage);
Hvis de kommer fint frem på skærmen burde det ikke være et problem, det er mest vigtigt i forhold til inputs